- name: p-metrics
  metadata_basename: p_metrics
  product_slug: ops-metrics
- name: p-mysql
  metadata_basename: p_mysql
  product_slug: p-mysql
- name: p-push-notifications
  metadata_basename: p_push_notifications
  product_slug: p-push-notifications
- name: p-rabbitmq
  metadata_basename: p_rabbitmq
  product_slug: p-rabbitmq
- name: p-redis
  metadata_basename: p_redis
  product_slug: p-redis
- name: apm
  metadata_basename: apm
  product_slug: pcf-metrics
- name: p-spring-cloud-services
  metadata_basename: p_spring_cloud_services
  product_slug: p-spring-cloud-services
- name: p-scheduler
  metadata_basename: p_scheduler
  product_slug: p-scheduler-for-pcf